NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/{{.CertName}}.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/{{.CertName}}.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/{{.CertName}}.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/{{.CertName}}.pem
    OrganizationalUnitIdentifier: orderer